
# Site settings
title: Web开发过程中的胡言乱语
email: wangqiangshen@gmail.com
description: "专注于WEB开发，WEB设计，jQuery开发，Python开发，服务器优化，搜索引擎"
keywords: "Web开发,Web设计,Python,Linux,Elasticsearch,Big Data"
baseurl: ""
url: "http://tookit.github.com"
username: Michaelwang
paginate: 5
# Build settings
markdown: kramdown
# kramdown:
#     toc_levels: 1..3
permalink: pretty


#custom variable settings